### PR TITLE
Fix rollback in production, drop unused trait

### LINKED ISSUE #58: The "force" option does not exist when running doctrine:migrations:rollback
```
$ php artisan doctrine:migrations:rollback

                                                                  
  [Symfony\Component\Console\Exception\InvalidArgumentException]  
  The "force" option does not exist.                              
                                                                  

$ php artisan doctrine:migrations:rollback --force

                                                          
  [Symfony\Component\Console\Exception\RuntimeException]  
  The "--force" option does not exist.                    
                                                          
```

Either this command should not use `ConfirmableTrait` or it should add a `--force` option.

### PR DESCRIPTION
**Pull request by Jalle19**
Fixes #58 

@garret-gunter

### CODE REVIEW

**Comment by Jalle19** [comment]
Who should I ping to get this moving?

File: src/Console/ResetCommand.php [hunk 1]
```diff
@@ -5,12 +5,10 @@
 use Doctrine\DBAL\Connection;
 use Exception;
 use Illuminate\Console\Command;
-use Illuminate\Console\ConfirmableTrait;
 use LaravelDoctrine\Migrations\Configuration\ConfigurationProvider;
 
 class ResetCommand extends Command
 {
-    use ConfirmableTrait;
```
Comment (patrickbrouwers) [inline src/Console/ResetCommand.php]: Instead of removing, I'd prefer to see

```
if (!$this->confirmToProceed()) {
    return;
}
```

added. 

Running this in production should give a warning.

**Review by patrickbrouwers — CHANGES_REQUESTED** [review]

**Comment by Jalle19** [comment]
@patrickbrouwers done

**Review by patrickbrouwers — APPROVED** [review]
